#############################################################################
# Makefile for building: CoinFlip.app/Contents/MacOS/CoinFlip
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  CoinFlip.pro
# Template: app
# Command: /Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/qmake -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers -I../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers -I../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib
QMAKE         = /Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CoinFlip1.0.0
DISTDIR = /Users/pangyu/Documents/qt_projects/CoinFlip/.tmp/CoinFlip1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = chooselevelscene.cpp \
		main.cpp \
		mainscene.cpp \
		mypushbutton.cpp \
		playscene.cpp qrc_res.cpp \
		moc_chooselevelscene.cpp \
		moc_mainscene.cpp \
		moc_mypushbutton.cpp \
		moc_playscene.cpp
OBJECTS       = chooselevelscene.o \
		main.o \
		mainscene.o \
		mypushbutton.o \
		playscene.o \
		qrc_res.o \
		moc_chooselevelscene.o \
		moc_mainscene.o \
		moc_mypushbutton.o \
		moc_playscene.o
DIST          = ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qdevice.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/device_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/unix.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/macx.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/sanitize.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang-mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qconfig.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_functions.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/toolchain.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resolve_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_post.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qml_debug.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/mac.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/warn_on.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resources.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/moc.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/uic.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/thread.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qmake_use.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/file_copies.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/rez.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exceptions.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/yacc.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/lex.prf \
		CoinFlip.pro chooselevelscene.h \
		mainscene.h \
		mypushbutton.h \
		playscene.h chooselevelscene.cpp \
		main.cpp \
		mainscene.cpp \
		mypushbutton.cpp \
		playscene.cpp
QMAKE_TARGET  = CoinFlip
DESTDIR       = 
TARGET        = CoinFlip.app/Contents/MacOS/CoinFlip

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/pangyu/Documents/qt_projects/CoinFlip/CoinFlip.pro


include /Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

CoinFlip.app/Contents/MacOS/CoinFlip: ui_mainscene.h $(OBJECTS)  
	@test -d CoinFlip.app/Contents/MacOS/ || mkdir -p CoinFlip.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CoinFlip.pro ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang/qmake.conf ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qdevice.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/device_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/unix.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/macx.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/sanitize.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang-mac.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qconfig.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_functions.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/toolchain.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resolve_config.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_post.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qml_debug.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/mac.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/warn_on.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resources.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/moc.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/uic.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/thread.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qmake_use.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/file_copies.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/rez.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exceptions.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/yacc.prf \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/lex.prf \
		CoinFlip.pro \
		res.qrc \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_pre.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qdevice.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/device_config.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/unix.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/mac.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/macx.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/sanitize.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/common/clang-mac.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/qconfig.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_functions.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt_config.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/sdk.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/toolchain.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_pre.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resolve_config.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/default_post.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/default_post.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qml_debug.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/mac.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/warn_on.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qt.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/resources.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/moc.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/opengl.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/uic.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/unix/thread.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/qmake_use.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/file_copies.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/rez.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/testcase_targets.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/exceptions.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/yacc.prf:
../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/lex.prf:
CoinFlip.pro:
res.qrc:
../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

CoinFlip.app/Contents/PkgInfo: 
	@test -d CoinFlip.app/Contents || mkdir -p CoinFlip.app/Contents
	@$(DEL_FILE) CoinFlip.app/Contents/PkgInfo
	@echo "APPL????" > CoinFlip.app/Contents/PkgInfo
CoinFlip.app/Contents/Resources/empty.lproj: 
	@test -d CoinFlip.app/Contents/Resources || mkdir -p CoinFlip.app/Contents/Resources
	@touch CoinFlip.app/Contents/Resources/empty.lproj
	
CoinFlip.app/Contents/Info.plist: 
	@test -d CoinFlip.app/Contents || mkdir -p CoinFlip.app/Contents
	@$(DEL_FILE) CoinFlip.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.CoinFlip,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.CoinFlip,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,CoinFlip,g" -e "s,@LIBRARY@,CoinFlip,g" -e "s,\$${EXECUTABLE_NAME},CoinFlip,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang/Info.plist.app >CoinFlip.app/Contents/Info.plist

all: Makefile \
		CoinFlip.app/Contents/PkgInfo \
		CoinFlip.app/Contents/Resources/empty.lproj \
		CoinFlip.app/Contents/Info.plist CoinFlip.app/Contents/MacOS/CoinFlip

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents chooselevelscene.h mainscene.h mypushbutton.h playscene.h $(DISTDIR)/
	$(COPY_FILE) --parents chooselevelscene.cpp main.cpp mainscene.cpp mypushbutton.cpp playscene.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainscene.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CoinFlip.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/rcc \
		res/Coin0003.png \
		res/LevelWinSound.wav \
		res/Coin0004.png \
		res/Coin0005.png \
		res/MenuSceneStartButton.png \
		res/Coin0006.png \
		res/BoardNode.png \
		res/PlayLevelSceneBg.png \
		res/Coin0007.png \
		res/Coin0008.png \
		res/Coin0001.ico \
		res/BackButtonSelected.png \
		res/Title.png \
		res/BackButton.png \
		res/LevelIcon.png \
		res/TapButtonSound.wav \
		res/ConFlipSound.wav \
		res/OtherSceneBg.png \
		res/LevelCompletedDialogBg.png \
		res/myDouDZ.wav \
		res/MenuSceneBg.png \
		res/BackButtonSound.wav \
		res/Coin0001.png \
		res/Coin0002.png
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../../Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_chooselevelscene.cpp moc_mainscene.cpp moc_mypushbutton.cpp moc_playscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chooselevelscene.cpp moc_mainscene.cpp moc_mypushbutton.cpp moc_playscene.cpp
moc_chooselevelscene.cpp: chooselevelscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		playscene.h \
		moc_predefs.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/moc
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/moc $(DEFINES) --include /Users/pangyu/Documents/qt_projects/CoinFlip/moc_predefs.h -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang -I/Users/pangyu/Documents/qt_projects/CoinFlip -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib chooselevelscene.h -o moc_chooselevelscene.cpp

moc_mainscene.cpp: mainscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooselevelscene.h \
		playscene.h \
		moc_predefs.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/moc
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/moc $(DEFINES) --include /Users/pangyu/Documents/qt_projects/CoinFlip/moc_predefs.h -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang -I/Users/pangyu/Documents/qt_projects/CoinFlip -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib mainscene.h -o moc_mainscene.cpp

moc_mypushbutton.cpp: mypushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		moc_predefs.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/moc
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/moc $(DEFINES) --include /Users/pangyu/Documents/qt_projects/CoinFlip/moc_predefs.h -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang -I/Users/pangyu/Documents/qt_projects/CoinFlip -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib mypushbutton.h -o moc_mypushbutton.cpp

moc_playscene.cpp: playscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/moc
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/moc $(DEFINES) --include /Users/pangyu/Documents/qt_projects/CoinFlip/moc_predefs.h -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/mkspecs/macx-clang -I/Users/pangyu/Documents/qt_projects/CoinFlip -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers -I/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/lib playscene.h -o moc_playscene.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainscene.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainscene.h
ui_mainscene.h: mainscene.ui \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/bin/uic
	/Users/pangyu/Downloads/qt5.12.12/5.12.12/clang_64/bin/uic mainscene.ui -o ui_mainscene.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

chooselevelscene.o: chooselevelscene.cpp chooselevelscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		playscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		mypushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chooselevelscene.o chooselevelscene.cpp

main.o: main.cpp mainscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooselevelscene.h \
		playscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainscene.o: mainscene.cpp mainscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		chooselevelscene.h \
		playscene.h \
		ui_mainscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		mypushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainscene.o mainscene.cpp

mypushbutton.o: mypushbutton.cpp mypushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypushbutton.o mypushbutton.cpp

playscene.o: playscene.cpp playscene.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Downloads/qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playscene.o playscene.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_chooselevelscene.o: moc_chooselevelscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chooselevelscene.o moc_chooselevelscene.cpp

moc_mainscene.o: moc_mainscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainscene.o moc_mainscene.cpp

moc_mypushbutton.o: moc_mypushbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mypushbutton.o moc_mypushbutton.cpp

moc_playscene.o: moc_playscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playscene.o moc_playscene.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/CoinFlip/bin || mkdir -p $(INSTALL_ROOT)/opt/CoinFlip/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app
	
	-$(QINSTALL) CoinFlip.app $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/CoinFlip/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

